import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {ActivityStore} from '../src/activity.js';
function req({ua='mcp-client',ip='203.0.113.1',headers={}}={}){return{method:'POST',url:'/mcp',headers:{'user-agent':ua,'x-forwarded-for':ip,...headers},socket:{remoteAddress:ip}}}
test('MCP demo invocation does not count as verified stranger',()=>{const a=new ActivityStore();const r=req();a.record(r,{kind:'mcp',result:'tools/call:once_demo'});const s=a.snapshot();assert.equal(s.realUse.verifiedStrangers,0);assert.equal(s.feed[0].classification,'UNKNOWN_MACHINE')});
test('interactive MCP once_execute counts as credible real use',()=>{const a=new ActivityStore();const r=req({ua:'modelcontextprotocol-client'});a.record(r,{kind:'mcp',result:'initialize',clientInfo:{name:'Claude Desktop',version:'1.0'}});a.record(r,{kind:'mcp',result:'tools/call:once_execute'});const s=a.snapshot();assert.equal(s.realUse.verifiedStrangers,1);assert.equal(s.feed[0].classification,'CREDIBLE_REAL_USE');assert.equal(s.headline.discoveryCallsToday,1);assert.equal(s.headline.coreToolCallsToday,1)});
test('known validator never counts as stranger',()=>{const a=new ActivityStore();const r=req({ua:'Smithery MCP validator'});a.record(r,{kind:'mcp',result:'tools/call:once_execute'});const s=a.snapshot();assert.equal(s.realUse.verifiedStrangers,0);assert.equal(s.feed[0].classification,'KNOWN_VALIDATOR');assert.equal(s.headline.validatorCallsToday,1)});
test('authenticated production API call without affirmative stranger evidence fails closed',()=>{const a=new ActivityStore();const r=req({ua:'production-agent'});a.record(r,{kind:'once',result:'VERIFIED'});const s=a.snapshot();assert.equal(s.realUse.verifiedStrangers,0);assert.equal(s.feed[0].classification,'UNKNOWN_MACHINE')});
test('explicitly attributed external production API call can count as credible real use',()=>{const a=new ActivityStore();const r=req({ua:'production-agent',headers:{'x-once-source':'external-integration'}});a.record(r,{kind:'once',result:'VERIFIED'});assert.equal(a.snapshot().realUse.verifiedStrangers,1)});
test('bot and monitor traffic is separated from discovery and core use',()=>{const a=new ActivityStore();const r=req({ua:'Better Uptime monitor'});a.record(r,{kind:'mcp',result:'ping'});const s=a.snapshot();assert.equal(s.headline.monitoringCallsToday,1);assert.equal(s.headline.discoveryCallsToday,0);assert.equal(s.realUse.verifiedStrangers,0);assert.equal(s.feed[0].classification,'BOT_OR_MONITOR')});
test('activity persists without storing raw IP',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'once-activity-'));try{const a=new ActivityStore({dataDir:dir,callerSecret:'test-secret'});const r=req({ip:'198.51.100.77'});a.record(r,{kind:'mcp',result:'tools/list'});const raw=fs.readFileSync(path.join(dir,'once-activity.json'),'utf8');assert.equal(raw.includes('198.51.100.77'),false);const b=new ActivityStore({dataDir:dir,callerSecret:'test-secret'});assert.equal(b.snapshot().headline.discoveryCallsToday,1);assert.equal(b.snapshot().privacy.durableActivityStorage,true)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('snapshot labels Eastern display time explicitly',()=>{const s=new ActivityStore().snapshot();assert.equal(s.displayTimeZone,'America/New_York');assert.match(s.generatedAtEastern,/(EDT|EST)$/)});
