import crypto from 'node:crypto';
const MAX_EVENTS=5000;
const TEST_RE=/(github-actions|registry-check|curl|railway|healthcheck)/i;
const KNOWN_VALIDATOR_RE=/(smithery|glama|pulsemcp|mcp[- ]?registry|registry\.modelcontextprotocol|modelcontextprotocol.*registry)/i;
const INTERACTIVE_CLIENT_RE=/(claude|cursor|windsurf|vscode|visual studio code|chatgpt|openai|cline|roo|zed)/i;
function day(ts){return new Date(ts).toISOString().slice(0,10)}
function hash(value){return crypto.createHash('sha256').update(String(value||'unknown')).digest('hex').slice(0,12)}
function safe(v,max=256){const s=String(v||'').trim();return s?s.slice(0,max):null}
function source(req){const explicit=safe(req.headers['x-once-source'],64);if(explicit)return explicit;const ua=String(req.headers['user-agent']||'');if(/modelcontextprotocol|mcp/i.test(ua))return 'mcp-client';return 'direct'}
function internal(req){const ua=String(req.headers['user-agent']||'');return String(req.headers['x-once-internal']||'')==='1'||TEST_RE.test(ua)}
function classify(e){if(!e.external)return {classification:'CONTROLLED_TEST',reasons:['internal/test marker']};const text=[e.audit?.userAgent,e.audit?.clientInfo?.name,e.audit?.clientInfo?.version,e.audit?.origin,e.audit?.referrer,e.source].filter(Boolean).join(' ');if(KNOWN_VALIDATOR_RE.test(text))return {classification:'KNOWN_VALIDATOR',reasons:['known registry/directory/validator evidence']};if(e.kind==='once')return {classification:'CREDIBLE_REAL_USE',reasons:['authenticated production ONCE execution']};if(e.kind==='mcp'&&e.result==='tools/call:once_execute'&&INTERACTIVE_CLIENT_RE.test(e.audit?.clientInfo?.name||''))return {classification:'CREDIBLE_REAL_USE',reasons:[`interactive MCP client: ${e.audit.clientInfo.name}`]};if(e.kind==='demo'||e.kind==='trial')return {classification:'CONTROLLED_TEST',reasons:['demo/trial path does not count as stranger production use']};if(e.kind==='mcp'&&String(e.result||'').startsWith('tools/call'))return {classification:'UNKNOWN_MACHINE',reasons:['core/demo MCP tool invocation','insufficient evidence to prove genuine stranger']};return {classification:null,reasons:[]}}
export class ActivityStore{
 constructor(){this.events=[];this.clientInfo=new Map()}
 record(req,{kind,status=200,result=null,clientInfo=null}={}){const ip=String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.socket?.remoteAddress||req.headers['user-agent'];const caller=hash([ip,req.headers['user-agent']||'',req.headers['accept-language']||''].join('|'));if(clientInfo?.name)this.clientInfo.set(caller,{name:safe(clientInfo.name,80),version:safe(clientInfo.version,40)});const e={id:crypto.randomUUID(),at:new Date().toISOString(),kind,status,result,source:source(req),channel:kind==='mcp'?'mcp':'rest',caller,external:!internal(req),auditVersion:2,audit:{userAgent:safe(req.headers['user-agent'],512),acceptLanguage:safe(req.headers['accept-language'],128),origin:safe(req.headers.origin,256),referrer:safe(req.headers.referer||req.headers.referrer,256),via:safe(req.headers.via,128),forwardedHost:safe(req.headers['x-forwarded-host'],128),requestMethod:safe(req.method,16),requestPath:safe(req.url,128),clientInfo:this.clientInfo.get(caller)||null}};const c=classify(e);e.classification=c.classification;e.classificationReasons=c.reasons;this.events.unshift(e);if(this.events.length>MAX_EVENTS)this.events.length=MAX_EVENTS;return e}
 snapshot(){const today=day(Date.now()),external=this.events.filter(e=>e.external),todays=external.filter(e=>e.at.slice(0,10)===today),credible=external.filter(e=>e.classification==='CREDIBLE_REAL_USE');return {service:'ONCE',generatedAt:new Date().toISOString(),external:{callsToday:todays.length,uniqueCallersToday:new Set(todays.map(e=>e.caller)).size,mcpCallsToday:todays.filter(e=>e.kind==='mcp').length,apiCallsToday:todays.filter(e=>e.kind==='once').length,demoCallsToday:todays.filter(e=>e.kind==='demo').length,trialKeysToday:todays.filter(e=>e.kind==='trial').length,lastCall:external[0]?.at||null},realUse:{verifiedStrangers:new Set(credible.map(e=>e.caller)).size,credibleCalls:credible.length},verificationPolicy:{version:2,rule:'Tool invocation is evidence of use, not automatically evidence of a real stranger. Only CREDIBLE_REAL_USE counts.',classes:['KNOWN_VALIDATOR','LIKELY_VALIDATOR','CONTROLLED_TEST','UNKNOWN_MACHINE','CREDIBLE_REAL_USE']},privacy:{rawIpStored:false,requestPayloadStored:false,credentialsStored:false},all:{callsToday:this.events.filter(e=>e.at.slice(0,10)===today).length},feed:external.slice(0,100)}}
}
